apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-2
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  project: default
  source:
    chart: prometheus
    helm:
      values: |
        pushgateway:
          enabled: false
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 13.0.3
  syncPolicy:
    automated:
      prune: true